// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttjwrwigqzhteljqgsor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0andyd2lncXpodGVsanFnc29yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODk3NDQsImV4cCI6MjA2OTg2NTc0NH0.-J1cyiuAC5gZYtvODQrZGOGzwZZ1bFzNhM8YEeUtKcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});